/* THIS FILE IS CLOSED FOR EDITING. YOU SHOULD MAKE CHANGES IN A NEW SQL FILE */

ALTER TABLE assessments ALTER COLUMN description TYPE VARCHAR(1000);
ALTER TABLE comments ALTER COLUMN post TYPE VARCHAR(1000);

/* THIS FILE IS CLOSED FOR EDITING. YOU SHOULD MAKE CHANGES IN A NEW SQL FILE */
